# Generated by Django 2.0.4 on 2018-10-08 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='closing_timw',
            new_name='closing_time',
        ),
    ]
